server:
  port: ${consumerport:8081}
spring:
  datasource:
    url: jdbc:postgresql://${DBHOSTNAME}:5432/${DBCONSUMERNAME}
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:9092
    properties:
      sasl:
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username=${kafka_username:'admin'} password=${kafka_password:'admin'};
        mechanism: PLAIN
      security:
        protocol: SASL_PLAINTEXT
    consumer:
      auto-offset-reset: earliest
      group-id: my-group
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      max-poll-records: 1
      fetch-max-wait: 36000
      enable-auto-commit: false
      client-id: consumer
      jaas:
        enabled: true
      properties:
        spring:
          json:
            trusted:
              packages: ru.dtimofeev.springapp.models
    listener:
      poll-timeout: 1800000
      concurrency: 1
      ack-mode: manual_immediate
  flyway:
    enabled: true

  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n"
  level:
    root: INFO
    ru.dtimofeev.springapp.aop: INFO
  file:
    name: logs/aspect.log