spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: user
    password: 123
    driver-class-name: org.h2.Driver
    initialization-mode: always

  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
      enabled: true

  flyway:
    enabled: true

  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n"
  level:
    root: INFO
    ru.dtimofeev.springapp.aop: INFO
  file:
    name: logs/aspect.log