spring:
  datasource:
    url: jdbc:postgresql://mydb:5432/appdb
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true

  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n"
  level:
    root: INFO
    ru.dtimofeev.springapp.aop: INFO
  file:
    name: logs/aspect.log